import { AnalysisResult } from './analyzer';

// Demo data for testing when CORS proxies are unavailable
export function getDemoData(url: string): AnalysisResult {
  const isExpomap = url.includes('expomap.ru');
  const isNicConf = url.includes('nic-conf.ru');
  
  if (isExpomap) {
    return getExpomapDemoData(url);
  } else if (isNicConf) {
    return getNicConfDemoData(url);
  } else {
    return getGenericDemoData(url);
  }
}

function getExpomapDemoData(url: string): AnalysisResult {
  return {
    url,
    title: 'Неделя безопасности Техэксперт 2026 - конференция по охране труда',
    description: 'Онлайн-конференция по комплексной безопасности предприятий',
    fetchedAt: new Date().toISOString(),
    htmlSize: 245000,
    hasSSL: true,
    hasTitle: true,
    titleLength: 65,
    hasMetaDescription: true,
    metaDescriptionLength: 145,
    hasMetaKeywords: false,
    hasCanonical: true,
    hasOpenGraph: true,
    hasTwitterCard: false,
    hasRobots: true,
    hasViewport: true,
    hasCharset: true,
    hasLang: true,
    h1Count: 1,
    h2Count: 4,
    h3Count: 2,
    totalHeadings: 7,
    totalParagraphs: 12,
    totalImages: 8,
    imagesWithoutAlt: 2,
    totalLinks: 45,
    externalLinks: 12,
    internalLinks: 33,
    hasFavicon: true,
    wordCount: 850,
    hasHttps: true,
    usesWww: false,
    hasForms: true,
    hasVideo: false,
    hasIframe: false,
    hasInlineStyles: 15,
    hasScripts: 18,
    hasCssLinks: 3,
    hasJsonLd: true,
    hasSitemap: true,
    hasRobotsTxt: true,
    contentScore: 78,
    uxScore: 82,
    seoScore: 75,
    technicalScore: 85,
    overallScore: 80,
    issues: [
      {
        id: 'seo1',
        title: 'Отсутствуют Twitter Card теги',
        description: 'Не найдены мета-теги для Twitter Card.',
        severity: 'low',
        category: 'seo',
        recommendation: 'Добавьте <meta name="twitter:card" content="summary_large_image"> и связанные теги.',
        impact: 'Красивые карточки при публикации в Twitter/X',
      },
      {
        id: 'content1',
        title: 'Изображения без alt-текста (2 из 8)',
        description: '25% изображений не имеют атрибута alt.',
        severity: 'medium',
        category: 'content',
        recommendation: 'Добавьте описательные alt-атрибуты ко всем изображениям.',
        impact: 'Улучшение доступности и SEO',
      },
      {
        id: 'content2',
        title: 'Отсутствует видеоконтент',
        description: 'На странице не найдено видео.',
        severity: 'low',
        category: 'content',
        recommendation: 'Добавьте видео: обзор, инструкцию или презентацию.',
        impact: 'Увеличение времени на странице на 50-80%',
      },
    ],
    foundMetaTags: [
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'description', content: 'Онлайн-конференция по комплексной безопасности предприятий' },
      { name: 'robots', content: 'index, follow' },
      { name: 'og:title', content: 'Неделя безопасности Техэксперт 2026' },
      { name: 'og:description', content: 'Онлайн-конференция по комплексной безопасности' },
    ],
    foundHeadings: [
      { level: 1, text: 'Неделя безопасности Техэксперт 2026' },
      { level: 2, text: 'О конференции' },
      { level: 2, text: 'Программа конференции' },
      { level: 2, text: 'Для кого' },
      { level: 2, text: 'Организаторы' },
    ],
  };
}

function getNicConfDemoData(url: string): AnalysisResult {
  return {
    url,
    title: 'XXI Всероссийская научно-практическая конференция «Связь. Перспективы. Технологии 2030»',
    description: 'Наука, промышленность и образование в одном пространстве для обмена опытом',
    fetchedAt: new Date().toISOString(),
    htmlSize: 185000,
    hasSSL: true,
    hasTitle: true,
    titleLength: 85,
    hasMetaDescription: true,
    metaDescriptionLength: 95,
    hasMetaKeywords: false,
    hasCanonical: false,
    hasOpenGraph: true,
    hasTwitterCard: false,
    hasRobots: false,
    hasViewport: true,
    hasCharset: true,
    hasLang: true,
    h1Count: 1,
    h2Count: 3,
    h3Count: 5,
    totalHeadings: 9,
    totalParagraphs: 15,
    totalImages: 12,
    imagesWithoutAlt: 5,
    totalLinks: 28,
    externalLinks: 8,
    internalLinks: 20,
    hasFavicon: true,
    wordCount: 650,
    hasHttps: true,
    usesWww: false,
    hasForms: true,
    hasVideo: false,
    hasIframe: false,
    hasInlineStyles: 8,
    hasScripts: 12,
    hasCssLinks: 2,
    hasJsonLd: false,
    hasSitemap: false,
    hasRobotsTxt: false,
    contentScore: 68,
    uxScore: 72,
    seoScore: 58,
    technicalScore: 70,
    overallScore: 67,
    issues: [
      {
        id: 'seo1',
        title: 'Слишком длинный title',
        description: 'Длина title: 85 символов. Рекомендуется не более 60-70 символов.',
        severity: 'medium',
        category: 'seo',
        recommendation: 'Сократите title до 60 символов.',
        impact: 'Улучшение отображения в поисковой выдаче',
      },
      {
        id: 'seo2',
        title: 'Отсутствует canonical URL',
        description: 'Не найден тег <link rel="canonical">.',
        severity: 'medium',
        category: 'seo',
        recommendation: 'Добавьте <link rel="canonical" href="...">',
        impact: 'Предотвращение дублирования контента',
      },
      {
        id: 'seo3',
        title: 'Отсутствует файл robots.txt',
        description: 'Не найден файл /robots.txt.',
        severity: 'low',
        category: 'seo',
        recommendation: 'Создайте файл robots.txt.',
        impact: 'Контроль над индексацией сайта',
      },
      {
        id: 'seo4',
        title: 'Отсутствует структурированная разметка (JSON-LD)',
        description: 'Не найдена микроразметка Schema.org.',
        severity: 'medium',
        category: 'seo',
        recommendation: 'Добавьте JSON-LD разметку.',
        impact: 'Расширенные сниппеты в поиске',
      },
      {
        id: 'content1',
        title: 'Изображения без alt-текста (5 из 12)',
        description: '42% изображений не имеют атрибута alt.',
        severity: 'high',
        category: 'content',
        recommendation: 'Добавьте alt-атрибуты ко всем изображениям.',
        impact: 'Улучшение доступности и SEO',
      },
    ],
    foundMetaTags: [
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'description', content: 'Наука, промышленность и образование в одном пространстве' },
      { name: 'og:title', content: 'Связь. Перспективы. Технологии 2030' },
    ],
    foundHeadings: [
      { level: 1, text: 'Связь. Перспективы. Технологии 2030' },
      { level: 2, text: 'О конференции' },
      { level: 2, text: 'Направления' },
      { level: 2, text: 'Контакты' },
    ],
  };
}

function getGenericDemoData(url: string): AnalysisResult {
  return {
    url,
    title: 'Демонстрационный сайт',
    description: 'Это демонстрационный анализ сайта',
    fetchedAt: new Date().toISOString(),
    htmlSize: 150000,
    hasSSL: true,
    hasTitle: true,
    titleLength: 50,
    hasMetaDescription: true,
    metaDescriptionLength: 120,
    hasMetaKeywords: false,
    hasCanonical: true,
    hasOpenGraph: true,
    hasTwitterCard: false,
    hasRobots: true,
    hasViewport: true,
    hasCharset: true,
    hasLang: true,
    h1Count: 1,
    h2Count: 3,
    h3Count: 2,
    totalHeadings: 6,
    totalParagraphs: 10,
    totalImages: 5,
    imagesWithoutAlt: 1,
    totalLinks: 25,
    externalLinks: 5,
    internalLinks: 20,
    hasFavicon: true,
    wordCount: 500,
    hasHttps: true,
    usesWww: false,
    hasForms: true,
    hasVideo: false,
    hasIframe: false,
    hasInlineStyles: 10,
    hasScripts: 15,
    hasCssLinks: 2,
    hasJsonLd: false,
    hasSitemap: true,
    hasRobotsTxt: true,
    contentScore: 72,
    uxScore: 75,
    seoScore: 70,
    technicalScore: 78,
    overallScore: 74,
    issues: [
      {
        id: 'seo1',
        title: 'Отсутствуют Twitter Card теги',
        description: 'Не найдены мета-теги для Twitter Card.',
        severity: 'low',
        category: 'seo',
        recommendation: 'Добавьте Twitter Card теги.',
        impact: 'Улучшение превью в Twitter',
      },
      {
        id: 'content1',
        title: 'Изображения без alt-текста (1 из 5)',
        description: '20% изображений не имеют атрибута alt.',
        severity: 'medium',
        category: 'content',
        recommendation: 'Добавьте alt-атрибуты.',
        impact: 'Улучшение доступности',
      },
    ],
    foundMetaTags: [
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'description', content: 'Демонстрационный сайт' },
    ],
    foundHeadings: [
      { level: 1, text: 'Главная страница' },
      { level: 2, text: 'О нас' },
      { level: 2, text: 'Услуги' },
    ],
  };
}
